# Generated by Django 2.2.7 on 2019-11-28 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectxapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proyecto',
            name='arquitecto',
        ),
        migrations.AddField(
            model_name='proyecto',
            name='arquitecto_id',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
    ]
