# Generated by Django 2.2.7 on 2019-11-28 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectxapp', '0003_auto_20191128_1348'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tarea',
            name='activo',
        ),
        migrations.AddField(
            model_name='tarea',
            name='estado',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
