# Generated by Django 2.2.7 on 2019-11-28 23:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projectxapp', '0004_auto_20191128_1838'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tarea',
            old_name='estado',
            new_name='estados',
        ),
    ]
